openapi: 3.0.0
info:
  title: Character API
  version: 1.0.0
  description: API for managing characters
paths:
  /character:
    post:
      summary: Create a character
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                nickname:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                address:
                  type: string
                active:
                  type: boolean
              required:
                - name
                - surname
                - nickname
                - email
                - phone
                - address
                - active
      responses:
        '200':
          description: OK
  /character/{characterId}:
    get:
      summary: Retrieve a character
      parameters:
        - in: path
          name: characterId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    patch:
      summary: Update a character
      parameters:
        - in: path
          name: characterId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                nickname:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                address:
                  type: string
                active:
                  type: boolean
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a character
      parameters:
        - in: path
          name: characterId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
