name: docker-deploy


on:
  push:
    branches: 
      - 'main'


env:
  DOCKER_IMAGE: gandalfran/mock-api-crud


jobs:

  update_docker: 
    name: build and push image
    runs-on: ubuntu-latest
    steps:  
    
    - name: download new changes
      uses: actions/checkout@v2
    
    - name: setup QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: setup Docker build
      uses: docker/setup-buildx-action@v1

    - name: login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: mock-api-crud
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: build and push image to DockerHub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE }}
